export default {
  GITHUB_CLIENT_ID: import.meta.env.VITE_GITHUB_CLIENT_ID,
  GITHUB_CLIENT_SECRET: import.meta.env.VITE_GITHUB_CLIENT_SECRET,
  SERVER_PATH: import.meta.env.VITE_SERVER_PATH,
  SERVER_URL: import.meta.env.VITE_SERVER_URL,
  WEBRTC_VIDEO_MAX_BITRATE: import.meta.env.VITE_WEBRTC_VIDEO_MAX_BITRATE,
  WEBRTC_VIDEO_MAX_FRAME: import.meta.env.VITE_WEBRTC_VIDEO_MAX_FRAME,
  WEBRTC_RESOLUTION_SCALE_FACTOR: import.meta.env
    .VITE_WEBRTC_VIDEO_RESOLUTION_SCALE_FACTOR,
};
